# Generated by Django 4.1.3 on 2023-01-10 18:58

import apps.common.media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_is_verified_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/images/profiles/profile_default.png",
                null=True,
                upload_to=apps.common.media_path.profile_avatar_path,
            ),
        ),
    ]
