# Generated by Django 4.1.3 on 2023-01-11 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0002_debitcard_wallet_delete_sparecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitcard",
            name="card_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="card_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallet_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
