# Generated by Django 4.1.3 on 2023-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_debitcard_card_user_wallet_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitcard",
            name="card_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
