# Generated by Django 4.1.3 on 2023-01-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_debitcard_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitcard",
            name="card_number",
            field=models.CharField(
                default="5387901203874566", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_number",
            field=models.CharField(
                default="5387908307216545", max_length=255, unique=True
            ),
        ),
    ]
